### ISSUE TITLE
Макети

### ISSUE THREAD

**Issue by kohutd** [kohutd/diia#15]
### Проблема

Проблеми як такої немає, але було би класно мати конструкції для абстрагування структур через щось схоже на інтерфейси в ООП.

Чернетка:

```
макет Двигун
  запустити()
  зупинити()
кінець

структура ІоннийДвигун є Двигун
  ;; властивості двигуна
кінець

дія ІоннийДвигун.запустити()
  ;; ...
кінець

дія ІоннийДвигун.зупинити()
  ;; ...
кінець
```

### Пропозиція

Обговорити тут.

**Comment by dkostmii** [comment]
`Преставляє` чи `уособлює`?

**Comment by dkostmii** [comment]
Можливо, навіть `втілює`
