### ISSUE TITLE
Узагальнення?

### ISSUE THREAD

**Issue by kohutd** [kohutd/diia#33]
Для хорошої типизації варто мати Generics. Українською це хтось переклав як "Узагальнення".  Впринципі, непоганий варіант для слова, хоча, можливо, є ще варіанти. Але слово не проблема.

Поки не впевнений, що можна придумати щось дуже краще з того що вже є, тому:

Приклад узагальнення списку:
```
числа список<число> = [1, 2, 3]
```

словника:
```
слова словник<текст, текст> = (
  "лайк"="вподобайка",
  "баг"="вада"
)
```

структури:
```
структура Тварина<Г, Ш, Т, К>
  голова Г
  шия Ш
  тулуб Т
  кінцівки К
кінець

т = Тварина<МудраГолова, СильнаШия, НепробивнийТулуб, ГнучкіКінцівки>(...)
```

to be continued

**Comment by denkisil** [comment]
я спочатку збентежився, коли побачив надпис "Узагальнення?". думав, що узагальнювати збирались...
