### ISSUE TITLE
Перевірка типів

### ISSUE THREAD

**Issue by kohutd** [kohutd/diia#4]
### Проблема

Наразі Мавка не перевіряє типи. Це зроблено, щоб програми виконувались швидше.

Тим не менше, під час розробки функція перевірки типів може дуже добре допомогти.

Пропозиція додати прапорець до команди виконання мавки і назвати його "--увімкнути-перевірку-типів". Коли цей прапорець присутній, код буде виконуватись з перевіркою типів.

### Приклад:

**тест.м**:
```
а число = "сонце сяє, вітер віє"
```

**команда**:
```
мавка --увімкнути-перевірку-типів тест.м
```

**приклад результату**:
```
Не вдалось зловити: Неможливо присвоїти значення "сонце сяє, вітер віє" (текст) змінній "а" (число) через несумісність типів.
```

**Comment by harnyk** [comment]
Питання 1. Наскільки глибокою має бути типізація?

Наприклад, чи існуватиме можливість для типу "список чисел", "список текстів", "дія, що має аргументом число і повертає строку"?

Якщо уявити дженерики, що оголошуються за допомогою оператора `!(Т)`, то існуватимуть такі штуки:

```
а Список!(число) = Список()
а.додати("7")   ;;помилка
```

Питання 2. Автоматичний вивід типу.

Чи валідним буде наступний код?:

```
а = "п"   ;;чи тип автоматично визначиться як текст?
а = 7
```

Питання 3. Рефлексія

Чи буде механізм того, щоб дізнатися тип чогось в рантаймі?

```
а строка = "п"
б = тип(а)
друк(б)
```

**Comment by kant2002** [comment]
Зараз вуха JS торчать із Мавки, тому усі ігри із типами JS видно і у Мавці. Як писав у телезі
```
друк("b" + "a" + + "a"+ "a") // baNaNa
```
я так розумію без переверки типів це буде важко заборонити.

**Comment by harnyk** [comment]
й наразі будь-яка перевірка типів, якщо й можлива, то тільки в рантаймі. І це накладає певні обмеження.

Ну або треба писати компілятор
