### ISSUE TITLE
Вигляд шістнадцяткового числа

### ISSUE THREAD

**Issue by kohutd** [kohutd/diia#7]
### Проблема

Шістнадцяткове число у вигляді `0шАБВГҐД` виглядає дивно. Не думаю, що це сильна проблема, але можливо є інші способи репрезентувати такі числа. 

### Пропозиція

Пропоную це тут обговорити.

**Comment by denkisil** [comment]
я вважаю, що краще залишити шістнадцядкові числа такими, як вони є, тобто `0x00000`
я сумніваюсь в тому, що ці числа варто якось імплементувати на нашу мову. 
навіть якщо знайдеться варіант на нашій мові, то будуть деякі складнощі під час переводу з мавкових шістнадцяткових до шістнадцяткових в JS

**Comment by ArtemiiKravchuk** [comment]
Ну так, я думаю що краще їх або не додавати взагалі, або зробити в стандартному вигляді
Хоча якщо вже і будемо їх робити українською, то точно не можна використовувати Ґ...
Може щось типу 0шАБВГДЕ або 0шАВСДЕФ
