### ISSUE TITLE
Символ ділення

### ISSUE THREAD

**Issue by kohutd** [kohutd/diia#8]
### Проблема

Символ ділення `/` недоступний в загальноприйнятій українській розкладці клавіатури.

### Пропозиція

Пропоную обговорити це тут. Також, можливо, є сенс замінити його на `%`.

**Comment by romanfedyniak** [comment]
/ можна набрати на українській розкладці, якщо зажати шифт та "\"

**Comment by Korzhak** [comment]
> / можна набрати на українській розкладці, якщо зажати шифт та "\"

До мови треба давати додаткову інструкцію по використання української розкладки клавіатури:D

**Comment by romanfedyniak** [comment]
> 

ага, не всі до сих пір знають, як набрати "ґ" на клавіатурі

**Comment by Korzhak** [comment]
Пропоную розробити спеціальну клавіатуру для Мавки:D Щоб зі слежем і буквами A-F, аби не використовувати А-Д для шістнадцяткових числел))))))))))))00)0)

**Comment by bodamat** [comment]
> Але я невпевнений щодо макбуків, перевірте хтось

Так на макбуках повністю так само

**Comment by bodamat** [comment]
На макбуці він знаходиться трішки не в тому як напевно звикли. Він знизу клавіші esc, яка зверху лівому куті. Використовуючи shift є даний символ

**Comment by Korzhak** [comment]
На макбуці на двох розкладках української клавіатури (Ukrainian, Ukrainian Legacy) є слеші. Як зазначила @bodamat, на розкладці Ukrainian бекслеш знаходиться під Esc, там де в звичних клавіатурах тильда (~). При натисканні Shift + \ отримуємо(/.
В Ukrainian Legacy є сам символ слеша (/) там же, де і в англійській версії клавіатури.

Тому, ІМХО, не бачу проблеми використовувати звичний для всіх символ / для ділення.
